version: '3'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ./data/:/data/
    ports:
      - 90:80
    environment:
      - DOMAIN=https://vault.swaydb.cloud
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - ADMIN_TOKEN=$$argon2id$$v=19$$m=65540,t=3,p=4$$UkRFVGt5dUQxWEdiMExPeW5YMng0QkxmRytBRTRySFVrK0F4QkN0VUtPYz0$$cS2lrCTpnfrWa68thYgY4s7YjcxROFApGGCminNqZis
      #- SENDS_ALLOWED=true
      #- EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=true
      #- SIGNUPS_VERIFY=true
      #- SIGNUPS_VERIFY_RESEND_TIME=3600
      #- SIGNUPS_VERIFY_RESEND_LIMIT=5
      - SIGNUPS_DOMAINS_WHITELIST=swaydb.cloud
      #- SMTP_HOST=smtp.youremaildomain.com
      #- SMTP_FROM=vaultwarden@youremaildomain.com
      #- SMTP_FROM_NAME=Vaultwarden
      #- SMTP_SECURITY=SECURITYMETHOD
      #- SMTP_PORT=XXXX
      #- SMTP_USERNAME=vaultwarden@youremaildomain.com
      #- SMTP_PASSWORD=YourReallyStrongPasswordHere
      #- SMTP_AUTH_MECHANISM="Mechanism"
    volumes:
      - ./run/vaultwarden:/data
    #networks:
    #- no-internet
#networks:
 #no-internet:
   #internal: true
   #external: false
